### ISSUE TITLE
Use mdcm system libraries

### ISSUE THREAD

**Issue by alcir** [AlizaMedicalImaging/AlizaMS#3]
Hello again.
Let's suppose that I already have libmdcm*.so files installed on the system. I see that compiling alizams these libraries are also generated.
(Again, I'm not a developer). Is it difficult to tell to cmake to use the "system" ones?
I see there is this comment in `CMakeLists.txt`, so I think it isn't still possible.
```
    149 # TODO try system, if possible
    150 set(MDCM_LJPEG_LIBRARIES mdcmjpeg8 mdcmjpeg12 mdcmjpeg16)
```

**Comment by issakomi** [comment]
Alizams uses internal MDCM, it is built statically, purposely, i didn't want MDCM package dependency (probably such package doesn't exist). Currently i can't easily switch to external package. OpenJPEG, UUID, Charls, Zlib can be used from system (specially if system's ITK is used), there are related options (you may try cmake-gui to view options or in the cmake file). JPEG8/12/16 can only be build internally, they are special for DICOM (even on Debian ITK/GDCM use exception from policy to use everything from shared libs and add lintian-override rule, no other possibility for medical JPEG). I don't know that is the Fedora's policy, i build Aliza (another program, similar) rpm with ITK and everything else statically and rpmlint doesn't complain (0 errors, 0 warnings). ITK can be used from distribution, but the user will have to pull 500-600 MB or more of dependencies for ITK.
Sorry, i am not familiar with Fedora packaging, my rpm for other program is "binary", i build as i like and then package. I got once Debian build done for release (debina-10 folder), but was too lazy to promote it and mess with their policies. May be i shall do it later for Debian.

**Comment by issakomi** [comment]
BTW, it were better to skip option MDCM_USE_PVRG (i don't use it for Github or other releases), it is rather bad, require either system "pvrgjpeg" binary or own binary in the same folder and creates file in tmp folder, there will be many warnings.

**Comment by alcir** [comment]
I mean.
Aren't such libraries the same as https://github.com/AlizaMedicalImaging/MDCM?

I mean. If I compile and place them somewhere in the system, can I point to them?
Or I'm doing some confusion?

**Comment by issakomi** [comment]
> I mean. Aren't such libraries the same as https://github.com/AlizaMedicalImaging/MDCM?

Alizams uses files from [mdcm](https://github.com/AlizaMedicalImaging/AlizaMS/tree/master/mdcm) folder. The files are synced with MDCM, only several cmake files are different. I done it purposely, as i had done Debian package. MDCM is WIP, i do often changes, no other software uses it, AFAIK, except mine (non-free version), i prefer to have some freedom with it. It will be difficult to support, specially shared libraries, due to frequent changes. _You are right_, it could be useful to have the option to switch to system's MDCM later, but it not yet done. Rules for Debian package are [here](https://github.com/AlizaMedicalImaging/AlizaMS/blob/master/debian-10/rules). Cmake flags:

```
 -DALIZA_QT_VERSION:STRING=5 \
 -DCMAKE_SKIP_RPATH:BOOL=ON \
 -DMDCM_USE_SYSTEM_UUID:BOOL=ON \
 -DMDCM_USE_SYSTEM_ZLIB:BOOL=ON \
 -DMDCM_USE_SYSTEM_OPENJPEG:BOOL=ON \
 -DMDCM_USE_SYSTEM_CHARLS:BOOL=ON
```

I also add flag `-DUSE_FORCE_CXX14:BOOL=ON` for Debian 10 package, but only to avoid warnings (harmless) from distribution's ITK-vln, something like, "your cplusplus version is lower...", i hope it is not required.

**Comment by issakomi** [comment]
I have closed for now the issue, if fact, you are right, of course, it were elegant to use the library, the only problem i consider the library as WIP, not yet ready to publish and support.
